Add `flake8-bugbear` to the linter
jfkcooper/HOGBEN pull request #78
Opened 2023-09-06 12:14 UTC by Sjoerd1993

`flake8-bugbear` also checks for certain patterns that are likely to cause bugs. The ones that did show up are addressed in this PR. 

See [link](https://github.com/PyCQA/flake8-bugbear) for more details.

2023-09-06 12:38 UTC, Sjoerd1993 commented
Couldn't get the test to fail locally, rerunning the test here gives a pass as well. Not sure why it failed that one run in that one commit.

2023-09-06 13:54 UTC, jfkcooper requested changes
three identical comments. I guess it is a linting thing, but it doesn't sit well with me to set a default to None, when we can set it to `[]` and not have any type uncertainty

2023-09-06 13:54 UTC, jfkcooper commented on hogben/optimise.py
> +        contrasts = contrasts or []
Is it not better to set the default in the init to `contrasts: Optional[list] = [],` this evaluates to `None` if required and removes this line

2023-09-06 13:54 UTC, jfkcooper commented on hogben/visualise.py
> +    contrasts = contrasts or []
Is it not better to set the default in the init to contrasts: Optional[list] = [], this evaluates to None if required and removes this line

2023-09-06 13:54 UTC, jfkcooper commented on hogben/visualise.py
> +    contrasts = contrasts or []
Is it not better to set the default in the init to contrasts: Optional[list] = [], this evaluates to None if required and removes this line

2023-09-07 12:05 UTC, Sjoerd1993 commented
Sorry for being slightly late, but I've changed the default assignment to an else statement like `contrasts = [] if contrasts is None else contrasts`.

There's actually one issue that I saw [raised on StackOverflow](https://stackoverflow.com/questions/13710631/is-there-shorthand-for-returning-a-default-value-if-none-in-python) using the or operator, which I think is somewhat relevant:

`Note that this also returns "default" if x is any falsy value, including an empty list, 0, empty string, or even datetime.time(0) (midnight).`

As said before, `contrasts = contrasts or []` defaults to the first argument (so `contrasts = contrasts`) if `bool(contrasts) == True` and to the second argument (`contrasts = []`) if `bool(contrasts) == False`. This does lead to the (rare) scenario, that someone could parse `contrasts = 0`  as an argument, and that would pass perfectly fine without any errors, as `bool(0) == False`. So you really do lose a bit of your type safety.

This is not a problem using this slightly longer else statement. As that really enforces that argument actually _is_ the None object, and not just has an equal value or parses as the same boolean value. So it will only set `contrasts` to an empty list if `None` is actually given as argument (or when the argument is left blank obviously).
In practice it won't matter too much probably (it works perfectly fine, the only situation I could imagine this leading to a bug is someone setting contrasts to 0), but it does make the if/else construction a bit more robust anyway.

2023-09-08 06:53 UTC, jfkcooper approved these changes
This was something we should be careful of in future,, and something which I completely missed, so thanks for catching it and following up on it I guess your linting work has made it so we should catch these anyway

2023-09-08 06:53 UTC, merged